// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

/**
 *	Author: 지용현
 *	Date: 2026.01.06(2026.01.06) 
 *	필요한 GameplayTag 등록
 */

namespace NovaGameplayTags
{
	NOVA_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	NOVA_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	NOVA_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Zoom);
	NOVA_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	
	NOVA_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Faction_Player);
	NOVA_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Faction_Enemy);
	NOVA_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Faction_NPC);
	
	NOVA_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_QuickSlot_1);
	NOVA_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_QuickSlot_2);
	NOVA_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_QuickSlot_3);
	NOVA_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_QuickSlot_4);
	NOVA_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_QuickSlot_5);
	NOVA_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_QuickSlot_6);
	NOVA_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_QuickSlot_7);
	NOVA_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_QuickSlot_8);
	NOVA_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_QuickSlot_9);
	NOVA_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_QuickSlot_0);
	
	
}